### ISSUE TITLE
java.lang.IllegalStateException: Actor not in world.

### ISSUE THREAD

**Issue by perryBunn** [perryBunn/ENGR-1110-Team2-Project#1]
error thrown in terminal
> java.lang.IllegalStateException: Actor not in world. An attempt was made to use the actor's location while it is not in the world. Either it has not yet been inserted, or it has been removed.
        at greenfoot.Actor.failIfNotInWorld(Actor.java:711)
	at greenfoot.Actor.getX(Actor.java:164)
	at Perry.<init>(Perry.java:16)
	at Room.<init>(Room.java:17)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at greenfoot.core.Simulation.newInstance(Simulation.java:617)
	at greenfoot.platforms.ide.WorldHandlerDelegateIDE$3.run(WorldHandlerDelegateIDE.java:425)
	at greenfoot.core.Simulation.runQueuedTasks(Simulation.java:502)
	at greenfoot.core.Simulation.maybePause(Simulation.java:305)
	at greenfoot.core.Simulation.runContent(Simulation.java:218)
	at greenfoot.core.Simulation.run(Simulation.java:211)

so i have no idea why but when it compiles its not adding the object to the world and then its trying to call for its X

line15-17 in Perry.java
>Hero h = new Hero();
>int DistanceX = getX() - h.getX(); 
>int DistanceY = getY() - h.getY();

line13-18 in Room.java
 >//backgroundMusic.playLoop();
>Hero hero = new Hero();
>addObject(hero, 212, 212);
>
>Perry perry = new Perry();
>addObject(perry, 212, 112);

no idea what to do about it

**Comment by perryBunn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Perry - fleeing sprite - moves away from hero](https://trello.com/c/g6sos2Gc/15-perry-fleeing-sprite-moves-away-from-hero)

**Comment by julienlegault** [comment]
Check out the changes I made to your code in my branch. I think one of your issues was with not having an image to display the enemy, and also you lacked a constructor. Also you were trying to add a new hero inside your class, instead of finding the hero that was already in the world.
