### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 

### ISSUE THREAD

**Issue by perryBunn** [perryBunn/ENGR-1110-Team2-Project#10]
favorite
so when a enemy comes into contact with the hero the hero class is suppose to remove the enemy class with the same X and Y. it works the first time but throws an error immediately after that

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 
at java.util.ArrayList.rangeCheck(ArrayList.java:653) at java.util.ArrayList.get(ArrayList.java:429) 
at Hero.checkCollision(Hero.java:39) 
at Hero.act(Hero.java:23)
```
public void act()
{
    ...
    checkCollision();
    ...
}
private void checkCollision() 
{
    Actor 2 = (Actor)getWorld().getObjects(2.class).get(0);
    if(2.getX() == getX() & 2.getY() == getY()) {
        getWorld().removeObject(2);
    }
    Actor 1 = (Actor)getWorld().getObjects(1.class).get(0);
    if(1.getX() == getX() & 1.getY() == getY()) {
        getWorld().removeObject(1);
    }
    Actor 3 = (Actor)getWorld().getObjects(3.class).get(0);
    if(3.getX() == getX() & 3.getY() == getY()) {
        getWorld().removeObject(3);
    }
      if (Room.totalPeeps == 0) {
          setLocation(250,250);
          GreenfootImage img = getImage();
          img.setFont(img.getFont().deriveFont(30f));
          setImage(new GreenfootImage("YOU WIN!!" , 75, Color.WHITE, Color.BLACK));
          Greenfoot.stop();
    }
}

**Comment by perryBunn** [comment]
added a if statement to check for size before removing the class

**if ( getWorld().getObjects(Example.class).size() > 0 ) {**
            Actor example = (Actor)getWorld().getObjects(example.class).get(0);
            if(example.getX() == getX() & example.getY() == getY()) {
                getWorld().removeObject(example);
            }
        **}**
